### ISSUE TITLE
BUG - Custom point attributes are lost in from_dict call

### ISSUE THREAD

**Issue by TylerSchum** [highcharts-for-python/highcharts-core#113]
**Describe the bug**
When trying to attach custom properties to data points, the custom properties are lost when creating a `HighchartsOptions` object when calling `HighchartsOptions.from_dict()`.

**To Reproduce**
1. I have series data with points that contain custom attributes.
2. I create an options object using `HighchartsOptions.from_dict` using that series data.
3. I try to access those attributes in the tooltip formatter function.
4. I get back undefined for all custom attributes.

**Expected behavior**
I expect that the properties would be available on `this.point` when using the `formatter` function in tooltip. This is behavior I currently do in the JS library.

**Your Environment:**
 - OS: Windows
 - Python Version: 3.10
 - Highcharts JavaScript Version: 11.1

**Additional context**
This is being tested in a Jupyter notebook, but when printing the `options` object directly. The custom attributes are already removed, so I believe this is occurring during the `from_dict` method call.

```py
data = [
    {
        'y': 0.845,
        'CUSTOM_VALUE': 0.193
    },
    {
        'y': 0.267,
        'CUSTOM_VALUE': 0.0932
    }
]

categories = [
    'category1',
    'category2'
]

options_dict = {
    'chart': {'type': 'bar'},
    'xAxis': {
    'categories': categories,
    'title': {'text': 'Categories'}
    },
    'yAxis': {'title': {'text': 'Some Number'}},
    'series': [{'type': 'bar', 'name': 'My Series', 'data': data}],
    'title': {'text': 'Categories and Numbers'},
    'tooltip': {
        'formatter': """function () {
            return `
                <p><b>Category: </b>${this.point.category}</p><br>
                <p><b>Custom Val: </b>${this.point.CUSTOM_VALUE}</p><br>
            `
        }""",
        'useHTML': 'true'
    }
}

options = HighchartsOptions.from_dict(options_dict)
# At this point, options does not contain the CUSTOM_VALUE property in the series data
my_chart = highcharts.Chart.from_options(options)
my_chart.display()
# Tooltips show undefined in place of the expected value
```

**Comment by hcpchris** [comment]
Hi @TylerSchum :

So this isn't technically a bug, though I do understand how it might seem like it is. The approach you are adopting - setting custom properties directly on the data point object - is not actually the recommended approach for Highcharts (JS), and it is not something that can work at all within Highcharts for Python. It does work in JavaScript, but that's because your JavaScript code is operating within one namespace, and you are taking advantage of the basic mutability of JavaScript objects - but because Highcharts for Python has to be a little more rigorous in its approach to facilitate consistent serialization / deserialization between Python and JavaScript, I'm afraid that does not work within our context.

However, there *is* an officially supported way to do what you are trying to do, and it is in fact the same both for Highcharts (JS) and for Highcharts for Python. Both Highcharts JS and Highcharts for Python use a custom namespace on data points (and series) called ``.custom`` which can be used for storing these kind of ``CUSTOM_VALUE`` properties. You can find the docs on the JS side [here](https://api.highcharts.com/highcharts/series.bar.data.custom) and its corresponding Python property [here](https://core-docs.highchartspython.com/en/latest/api/options/series/data/bar.html#highcharts_core.options.series.data.bar.BarData.custom). 

This ``.custom`` property is present on all series classes, and on all data point classes, and in Python accepts a simple ``dict`` as its input. That ``dict`` can contain values like you have them, or even ``CallbackFunction`` instances if you want. Using the ``.custom`` property requires a (trivially simple) tweak to your code, and then it works as you would expect. Here's your code revised to show how it would work:

```python
from highcharts_core.options import HighchartsOptions
from highcharts_core.chart import Chart

data = [
    {
        'y': 0.845,
        'custom': {
            'CUSTOM_VALUE': 0.193
        }
    },
    {
        'y': 0.267,
        'custom': {
            'CUSTOM_VALUE': 0.0932
        }
    }
]

categories = [
    'category1',
    'category2'
]

options_dict = {
    'chart': {'type': 'bar'},
    'xAxis': {
    'categories': categories,
    'title': {'text': 'Categories'}
    },
    'yAxis': {'title': {'text': 'Some Number'}},
    'series': [{'type': 'bar', 'name': 'My Series', 'data': data}],
    'title': {'text': 'Categories and Numbers'},
    'tooltip': {
        'formatter': """function () {
            return `
                <p><b>Category: </b>${this.point.category}</p><br>
                <p><b>Custom Val: </b>${this.point.custom.CUSTOM_VALUE}</p><br>
            `
        }""",
        'useHTML': 'true'
    }
}

options = HighchartsOptions.from_dict(options_dict)
my_chart = Chart.from_options(options)
my_chart.display()
```

As you can see in the code above, I had to make the tooltip formatter reference ``${this.point.custom.CUSTOM_VALUE}`` rather than merely ``${this.point.CUSTOM_VALUE}``, and similarly I had to add the ``custom`` key to my ``data`` dict, but the net result is - I believe - exactly what you are looking for:

![image](https://github.com/highcharts-for-python/highcharts-core/assets/123704219/2b7d5dd6-0118-41fb-bdb4-16165b6232e1)

I'll close this for the time being as not-a-bug, but if you run into any other issues or have further questions, please feel free to re-open or file a new issue!

**Comment by hcpchris** [comment]
Closing as unplanned, since the clarification above hopefully resolves the issue. Please feel free to re-open as needed.
