### ISSUE TITLE
chart.to_js_literal() Generates extra ; for chart options

### ISSUE THREAD

**Issue by thesteed** [highcharts-for-python/highcharts-core#34]
**Describe the bug**
Looks like charty.py `to_js_literal()` adds an extra ; after appending the options. (I think there is also an extra comma, but I don't think it hurts anything)

**To Reproduce**
```

from highcharts_core.chart import Chart
from highcharts_core.global_options.shared_options import SharedOptions
from highcharts_core.options.series.area import LineSeries


shared_options = SharedOptions.from_js_literal('''{
  chart: {
        backgroundColor: {
            linearGradient: {
              x1: 0,
              x2: 0,
              y1: 1,
              y2: 1
            },
            stops: [
                [0, 'rgb(255, 255, 255)'],
                [1, 'rgb(240, 240, 255)']
            ]
        },
        type: 'line',
        borderWidth: 2,
        plotBackgroundColor: 'rgba(255, 255, 255, .9)',
        plotBorderWidth: 1
  },
  caption: {
      align: 'center',
      floating: true,
      margin: 20,
      verticalAlign: 'top'
  },
  credits: {
      enabled: true,
      href: 'https://www.somewhere.com',
      style: {
          color: '#cccccc',
          fontSize: '8px'
      },
      text: 'Highcharts for Python'
  }
}''')

chart = Chart(container='container', options=shared_options)
series1 = LineSeries(data=[['01/01/2023', 1], ['01/02/2023', 2], ['01/03/2023', 3], ['01/04/2023', 4]])
chart.add_series(series1)

html = '''<html><head><script src="https://code.highcharts.com/highcharts.js"></script><script type='javascript'>%s</script></head><body>Test<br/><div id="container"></div></body></html>''' % chart.to_js_literal()
print(html)
```

which outputs (condensed):

```
<html><head><script src="https://code.highcharts.com/highcharts.js"></script><script type='javascript'>document.addEventListener('DOMContentLoaded', function() {
new Highcharts.chart('container',
Highcharts.setOptions({
  caption: {...},
  chart: {
  backgroundColor: {...},
  borderWidth: 2,
  plotBackgroundColor: 'rgba(255, 255, 255, .9)',
  plotBorderWidth: 1,
  type: 'line'
},
  credits: {...},
  series: [{
  data: [{
  x: '01/01/2023',
  y: 1
},
{
  x: '01/02/2023',
  y: 2
},
{
  x: '01/03/2023',
  y: 3
},
{
  x: '01/04/2023',
  y: 4
}],
  type: 'line'
}]
});,
);
});</script></head><body>Test<br/><div id="container"></div></body></html>
```

**Expected behavior**
Render a line chart w/ the dates on the X axis and the corresponding numbers on the Y axis

**Your Environment:**
- OS: Ubuntu 20.04 LTS
- Python Version: 3.10.6
- Highcharts Python: 1.0.0

**Additional context**
I'm pretty new to hcharts so might be doing something wrong, sorry!

**Comment by hcpchris** [comment]
Ah, okay. In this case the extra ``;`` is not so much a bug, as it is an unintended consequence of a user error (or at least, an unforeseen user action that probably should get treated as an ``Exception``...)

What's happening is that you are passing a ``SharedOptions`` instance to the ``options`` parameter, rather than a ``HighchartsOptions`` option. The way your code is working, you are basically doing the following:

1. You are creating a ``SharedOptions`` instance. This lets you configure global options that will apply to all charts that are rendered on the same page (same browser tab/view). 
2. You are creating your ``Chart`` instance, and setting ``options = shared_options``.
3. When you are then serializing your ``Chart`` to a JS literal, the ``SharedOptions`` instance is getting serialized as it expects to be...as a standalone JavaScript statement which sets the Highcharts global options within your browser environment. However, in this case that standalone JavaScript statement is showing up where it shouldn't: *within* your Highcharts constructor.

This is not throwing an error because technically ``SharedOptions`` inherits from ``HighchartsOptions``, which is what the ``options`` parameter is expecting. In v.1.0.1, which I'll be releasing within the next hour, I'll add a fairly trivial type check to catch this kind of user error. However, in the meantime you have two alternative ways to proceed:

1. The easiest way is to simply use ``HighchartsOptions`` instead of ``SharedOptions``, like so:

    ```
    ...
    from highcharts_core.options import HighchartsOptions
  
    options = HighchartsOptions.from_js_literal(...)
    Chart(container='container', options = options)
    ```
    and all the rest the same as you have it. This will *not* configure global options across all of your charts, but it *will* 
    configure the options you want on *that* specific chart instance.

2. A second option, which would apply if you want to use ``SharedOptions`` and render multiple charts on one page using shared configuration settings, is to do the following:

    ```
    ...
    Chart(container='container')
    series1 = LineSeries(data=[['01/01/2023', 1], ['01/02/2023', 2], ['01/03/2023', 3], ['01/04/2023', 4]])
    chart.add_series(series1)

    html = '''<html><head><script src="https://code.highcharts.com/highcharts.js"></script><script 
    type='javascript'>%s\n%s</script></head><body>Test<br/><div id="container"></div></body></html>''' % (shared_options.to_js_literal(), chart.to_js_literal())
    ```

This should have the result in your ``<script/>`` tag of first placing the ``SharedOptions`` JavaScript statement that applies your global configuration, and then adding your chart with your ``LineSeries`` below that.

Hopefully that helps? In the meantime, I'll add a type check to catch and throw a ``HighchartsValueError`` if someone passes a ``SharedOptions`` instance to the ``options`` parameter in v.1.0.1 and close this issue once it's released.

**Comment by thesteed** [comment]
@hcpchris Awesome thank you! yes that was very clear and informative! I was looking at the demo's in jsfiddle and noticed that too, but figured it might be another way to do it since the chart actually still rendered (well, without desired series plotted as a line) once I removed the ;

**Comment by hcpchris** [comment]
No worries - happy to help! 

I've introduced the change to catch that kind of situation, and I'm merging it into ``develop`` and then eventually into ``master`` now, once it goes through our CI/CD pipeline. Once that's complete, it'll get released with v.1.0.1 and this issue will get auto-closed.
