### ISSUE TITLE
[Question] What is the bundle size of JS assets loaded by `highcharts-core`?

### ISSUE THREAD

**Issue by rdp1414** [highcharts-for-python/highcharts-core#48]
Hello Team,

I am analyzing [Highcharts Python](https://www.highcharts.com/blog/news/python-integration-highcharts/) in depth as a candidate for charting and visualization requirements for my team and stakeholders. I've few questions:
1. As I understand, as soon as user imports `from highcharts_core.chart import Chart` in code,  then entire Highcharts (JS) assets are loaded. Is my understanding correct?
2. If the previous point is correct, then what is the JS Bundle size that you're loading? This is important for performance analysis.
3. Is it possible to invoke python callback back from JavaScript? For example, is it possible to run a certain python code snippet, when user clicks on `legend` on the chart?

Can you please clarify the above queries? As I analyze and share my summary of `Highcharts Python` with my managers, I might ask more questions in this particular thread.

Thank You,
rdp1414

**Comment by rdp1414** [comment]
##### Question regarding Highcharts documentation

Highcharts-python has a long static dump of all nested python options with documentation. 
1. How did you generate such a big dump of documentation?
2. What are your future plans for maintaining the same?

**Comment by hcpchris** [comment]
Hi @rdp1414 : Thanks for your questions! I've answered your questions below, and I'll also close this issue for the time being. If you have other questions, please feel free to either re-open the issue or create a new issue.

Loading of JS Modules
===================
When you execute ``from highcharts_core.chart import Chart`` the Python software does *not* load any of the Javascript modules. The only thing that it is loading is the Python code related to our Chart class. The Javascript modules are in fact *only* loaded automatically when you are displaying a Chart visualization in a Jupyter Notebook context using the ``Chart.display()`` method. 

In all other circumstances, you would include the Highcharts (JS) modules that you need yourself in your HTML code, which lets you only load / select the ones you need (we recommend loading the minified ones, of course, for performance reasons - and also using the Highcharts CDN, also for performance reasons). You can find more information about the JS modules [here](https://www.highcharts.com/docs/getting-started/installation). Note that depending on which features you are using in your chart, you may need additional modules from Highcharts (JS) as well, but you can find those details in the documentation I linked above.

When rendering a Highcharts for Python chart within a Jupyter Notebook environment, then the library *does* load all of the Highcharts JS modules. They are loaded asynchronously to minimize performance impact, but they do get downloaded from the Highcharts CDN. If this is a context that matters from your perspective, let me know and I'll see if I can get a total download size. That being said, this behavior is actually one that is actively under development at the moment (see #12 ) and the next minor release of Highcharts Core for Python should:
* have Highcharts for Python *only* load the JS modules that are needed / used by the chart
* support the configuration of loading Python modules from an arbitrary environment (i.e. not using only the Highcharts CDN, but enabling you to pull the relevant modules from your own configured locations).

That's work that is in progress, and is slated for release in the next minor version (v.1.2).

Python Callback from within Javascript
==============================

This is technically possible, but it is a little more complex because it depends on how you are implementing your broader application. The way that I would recommend implementing something like this is as follows:

1. In your Python code, when assembling your chart I would include Javascript callback functions as appropriate. You can pass those Javascript callback functions in the appropriate properties as documented, which fire when certain events happen (e.g. when the legend is clicked).
2. In your Javascript event handler, you would include a callback to whatever Python application / API were serving your content. This depends entirely on the architecture of your application. For example, if you have a Flask or Django app, you might call an API endpoint to "do something" in response to the event that occurred in the Javascript/browser.
3. Your Python app then does whatever action you need it to do, which may include modifying the chart (in Python), which then gets propagated / distributed to your web front-end.

So it is definitely something that is doable, but it does require you to implement the glue / connection between your Javascript and Python environments as appropriate for the architecture that you are implementing.

Documentation
=================

For the documentation, we have a strict policy of documenting *all* of our classes, methods, functions, etc. Largely, that's because we believe that good documentation makes code usable for other teams. So maintaining that documentation is a *fundamental* practice that we hold to. As for how the documentation actually gets built, there's a couple things that happen:

1. We make sure during our code reviews that all properties, methods, classes, functions, etc. are documented using docstrings that conform to our style guide (see [contributor guidelines > documentation conventions](https://core-docs.highchartspython.com/en/latest/contributing.html#documentation-conventions) ).
2. For the comprehensive "component list" that serves as an API table of contents, we looked into a variety of automated methods to maintain that, but ultimately came to the conclusion that the best way to produce that at this stage is to manually assemble and maintain that list. We're planning at some point to try to automate it, but we have yet to find (or develop) a good tool to do so. For the moment, maintaining that is part of our basic code review practices.
3. Every time a new branch is created our CI/CD pipelines auto-generates our documentation and tests whether the documentation is produced correctly.
4. Every time new code is pulled into our ``develop`` branch (our pre-release branch), the documentation is automatically built using our CI/CD pipeline and published to our documentation host (ReadTheDocs).
5. Every time a new version is released, the documentation for the latest version is automatically built using our CI/CD pipeline and published to our documentation host (ReadTheDocs).

And that's pretty much it. The documentation is something we are fundamentally dedicated to maintaining because without it, a toolkit like Highcharts for Python would become unusable. So we're committed to maintaining it.

**Comment by hcpchris** [comment]
Hi @rdp1414 :

No worries - it depends heavily on the architecture of your application. The reason why you got that uncaught ``ReferenceError`` in Javascript is because your Javascript code (the ``function(evt) { ... }``) tried to directly reference a Python function (``on_click(...)``). That will not work directly, because your JavaScript code has to call whatever application is serving your Python code. Plus, if you are using ``chart.display()`` that tells me you are trying to operate in a Jupyter Notebook context, where this method I'm describing will not work to get a Python callback from within Javascript.

However, the pseudo-code example I below shows how this would work in a classic Python API-driven web model. The implementation specifics however will depend heavily on your architecture, as earlier mentioned.

First, let's assume you have an API endpoint that returns your core chart content (I'm assuming Flask for the sake of simplicity, but the principles are the same regardless of what framework you are using):

```
@charts.route('/charts/<chart_id>', methods = ['GET'])
def get_chart(chart_id):
    import seaborn as sns
    df = sns.load_dataset('iris')
    x = df.sepal_length.values
    y = df.petal_width.values

    from highcharts_core.chart import Chart
    ch = Chart()

    from highcharts_core.options.series.scatter import ScatterSeries
    scatter_series = ScatterSeries()
    scatter_series.data = [(x_i, y_i) for (x_i, y_i) in zip(x, y)]
    scatter_series.name = 'Iris'

    # Set https://api.highcharts.com/highcharts/series.scatter.point.events.click property.
    from highcharts_core.options.plot_options.points import Point, PointEvents
    scatter_series.point = Point(events=PointEvents(click=f"""function(evt) \{
        fetch('/charts/{chart_id}/points/' + evt.id, method = 'post');
    \}"""))

    ch.add_series(scatter_series)
    as_js_literal = ch.to_js_literal()

    chart_id = uuid.uuid4()
    save_chart_definition(chart_id, as_js_literal)

    return flask.Response(response = [as_js_literal], status = 200)
```

What this function does is it exposes an API endpoint at ``/charts/<chart_id>`` which a) creates a Chart definition, b) saves that chart definition with ID ``chart_id``, and then returns the chart definition to your web-based client.

Next, your web-based client renders the Javascript code that the above API endpoint returns.

Then, your Python code will need a second endpoint that provides your Python ``on_click`` handler:

```
@charts.route('/charts/<chart_id>/on_click/<point_id>`, methods = ['POST'])
def on_click(chart_id, point_id):
    chart = load_chart_definition(chart_id)
    point = get_point(chart, point_id)
    
    log.info(chart_id, point.x, point.y, point.name)

    # Do whatever else you need your server-side code to do.
    # Presumably this will produce some updated version of your chart configuration that you want to send to your web client.

    return flask.Response(response = [as_js_literal], status = 201)
```

what this function now does it loads the chart definition, gets the point information, and logs the relevant information. You can of course do whatever else you need to do in the server side of the application at that point. The functions ``save_chart_definition()``, ``load_chart_definition()``, and ``get_point()`` in the code snippets above are just placeholders, obviously, but the point is to show the interaction sequence. Basically it boils down to:

1. Your API generates your chart definition in Python. It then gives that definition to your Javascript client.
2. Your Javascript client renders your chart definition, which includes your Javascript event handler.
3. When a user clicks a point in your chart, your Javascript event handler fires and calls a different (Python) API endpoint.
4. Your Python API endpoint handles the ``on_click(...)`` logic you need it to handle, presumably returning something relevant to your (Javascript) web client.

Hopefully this clarifies? The exact way of implementing this depends heavily on how you are implementing your server and client-side applications, obviously. But the basic principle should work regardless of what frameworks / models you are using. However, as mentioned before, this approach will *not* work in the Jupyter context - only in a standard client/server-style application.
