### ISSUE TITLE
Understanding `xAxis` units for timeseries data

### ISSUE THREAD

**Issue by c-jamie** [highcharts-for-python/highcharts-core#60]
Hi there,

Using the below code, the Chart renders, but the date representations in the xAxis appear wrong.

It's displaying the date associated with `20` as `Tues, 20 Jan, 08:36:57.600`

```
from highcharts_core.chart import Chart
from highcharts_core.options.series.area import LineSeries
from highcharts_core.global_options.shared_options import SharedOptions
import pandas as pd
import datetime as dt
df2 = pd.DataFrame({'date':[dt.datetime(2023,1,1), dt.datetime(2023,1,2)], 'sales': [10,20]})

my_chart = Chart.from_pandas(df2,
                            property_map = {
                                'x': 'date',
                                'y': 'sales',
                            },
                            series_type = 'line')
my_chart.options.plot_options: {
        'series': {
            'marker': {
                'enabled': False,
                'radius': 5.5
            }
        }
    }
my_chart.options.x_axis = {
        'type': 'datetime',
        'dateTimeLabelFormats': {
            'month': '%e. %b',
            'year': '%b'
        },
        'title': {
            'text': 'Date'
        },
         'plotLines': [{
            'color': '#FF0000',
            'width': 2,
            'value': dt.datetime(2023,1,1).timestamp()
        }]
    }

my_chart.display()
my_chart.to_js_literal()
```

`js_literal` returns

```
"document.addEventListener('DOMContentLoaded', function() {\nHighcharts.chart(null,\n{\n  series: [{\n  data: [{\n  x: 1672531200.0,\n  y: 10\n},\n{\n  x: 1672617600.0,\n  y: 20\n}],\n  type: 'line'\n}],\n  xAxis: {\n  plotLines: [{\n  color: '#FF0000',\n  value: 1672531200.0,\n  width: 2\n}],\n  title: {\n  text: 'Date'\n},\n  type: 'datetime'\n}\n},\n);\n});"
```

How do I get the correct dates to display on the above chart?

Your Environment:

- OS: Windows, Jupyter Lab (notebook).
- Python Version: 3.11
- Highcharts Version: Installed Highcharts Python using pip install highcharts-core command.
`highcharts-core           1.1.1                    pypi_0    pypi`

**Comment by hcpchris** [comment]
My apologies, @c-jamie ! I made a mistake in my answer to #57: the Highcharts (JS) x-axis with ``type = 'datetime'`` expects values in *milliseconds* from the Unix epoch rather than *seconds* (a peculiarity of JavaScript where JS represents POSIX timestamps in milliseconds rather than the more common seconds), as a result the correct workaround is to use ``.timestamp() * 1000``, since the ``.timestamp()`` method returns the value in seconds. 

That's what seems to have been causing the odd behavior in the tooltip / visualization, and when I run tests of the visualization it seems to now be rendering correctly with that slight tweak.

This in fact uncovers a different bug where time series values are not being serialized properly, so I've updated my answer in the previous issue (#57), and I've filed a priority bug in #61 which will be fixed in the next patch release (one that is expected to go out this afternoon).

Once the new version is released (as soon as CI/CD processes complete), this issue, #61 , and #58 will all be auto-closed.

Thanks for helping us catch this issue!
