### ISSUE TITLE
'navigation' not implemented..?

### ISSUE THREAD

**Issue by maxxpower007** [highcharts-for-python/highcharts-core#86]
Hi,

I am trying to change the export icon (and add others) to a font icon. 
To do this I need to set allowHTML in the 'navigation' part, however, it doesn't seem to get converted:

Eg:

    hc_options = {
        'navigation': {
            'buttonOptions': {
                'useHTML': True
            }
        },
        'exporting': {
            'buttons': {
                'contextButton': {
                    'enabled': False
                },
                'exportButton': {
                    'text': '<i class="fa fa-download"></i>',
                    'onclick': 'function () { this.exportChart(); }'
                }
            }
        }
    }
    chart = Chart(options=hc_options)
    chart.to_dict()

Yields (notice the missing 'navigation'):

`{'userOptions': {'exporting': {'buttons': {'contextButton': {'enabled': False},
    'exportButton': {'text': '<i class="fa fa-download"></i>'}}}}}
`

**Comment by hcpchris** [comment]
Hi @maxxpower007 : Thanks for reporting this! I took a quick look, and it seems to be the same / very similar issue as in #84 : the `buttonOptions` property is mapping to the incorrect base-class, which is causing `buttonOptions` to get dropped (and in your example, that means that `navigation` is empty, which means that it gets trimmed out of the result). 

I'll take a closer look and patch this in v.1.3.3 which will go out today - this should have been caught in yesterday's bugfix for #84 , but it looks to have slipped through the cracks.

**Comment by hcpchris** [comment]
Just confirming, there was a bug, and it was similar (though not the same) as in #84. The bug has been fixed in v.1.3.3 which was just released, and so the `navigation.buttonOptions` should no longer be dropped during serialization.

**Comment by maxxpower007** [comment]
Perfect..!
Confirmed working..

**Comment by maxxpower007** [comment]
Half working.. :)

    hc_options = {
        'navigation': {
            'buttonOptions': {
                'theme': {
                    'style': {
                        'fontSize': '30px',
                        'color': '#888'
                    },
                    'states': {
                        'hover': {
                            'style': {
                                'color': '#000'
                            }
                        }
                    }
                },
                'useHTML': True
            }
        }
    }
    chart = Chart(options=hc_options)
    chart.to_dict()

Yields (notice the missing theme):

`{'userOptions': {'navigation': {'buttonOptions': {'useHTML': True}}}}`

**Comment by hcpchris** [comment]
Hrm. Looks like there's an issue in the `ButtonTheme` class. I'll take a closer look tomorrow and do a deep dive on the whole `Navigation` module - clearly looks like some things were missed in there (and that our testing missed - the unit tests I checked today covered the `ButtonTheme` class, so there must be something odd happening in there). Either way - I'll do a deeper dive over the weekend. Sorry for the trouble!

**Comment by maxxpower007** [comment]
Not a big issue... I should probably be using css styling to theme anyways. 
Cheers

**Comment by hcpchris** [comment]
Hi @maxxpower007 - Turns out not to be a bug in the first place. It seems that Highcharts (JS) supports fairly broad extensibility when configuring `buttonOptions.theme`. They have only explicitly documented a limited number of properties, namely `fill`, `padding`, and `stroke`. As a result, these were properties implemented in Highcharts for Python. However, when running a variety of tests it turns out that `buttonOptions.theme` in the Highcharts JavaScript library supports most attribute that conform to CSS / styling, as well as the Highcharts-standard `states` attribute. It's not documented in the Highcharts API docs, so we hadn't implemented that extensibility before.

However, in v.1.3.4 which (which was just released), I have added that extensibility. Which means that what you are attempting to do should now work, and you should be able to configure the button's theme using `buttonOptions.theme`.

That being said, there is one issue in your code up above, particularly as relates to the `states` configuration. Highcharts `states` supports attributes like `hover`, etc. as you have it. But the `states.hover` attribute does not support a `style` attribute. It instead has a more explicit set of attributes that it supports - including the `color` attribute - which you will find [documented here](https://core-docs.highchartspython.com/en/latest/api/utility_classes/states.html#class-hoverstate). So to accomplish what you are trying to do successfully, you should use a slightly tweaked structure:

```
hc_options = {
    'navigation': {
        'buttonOptions': {
            'theme': {
                'style': {
                    'fontSize': '30px',
                    'color': '#888'
                },
                'states': {
                    'hover': {
                        'color': '#000'
                    }
                }
            },
            'useHTML': True
        }
    }
}
chart = Chart(options=hc_options)
chart.to_dict()
```
So with that, if you upgrade to the new version the theming you're trying to apply should now work as expected. Sorry for the trouble!
